# Generated by Django 3.2.9 on 2021-12-03 17:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0002_fooditem_order'),
    ]

    operations = [
        migrations.AddField(
            model_name='food',
            name='image',
            field=models.ImageField(default=None, upload_to='food_images/'),
            preserve_default=False,
        ),
    ]
